name: C/C++ CI

on:
  push:
    branches: [ main ]
    
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 
      run: |
        make sonixflasher
        tar -cvf sonixflasherc-linux.tar.xz sonixflasher
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: Upload Artifact
        path: sonixflasherc-linux.tar.xz
